# default parameter values
ifeq ($(ARCH),)
  UNAME := $(shell uname -s)
  ifeq ($(findstring MINGW64, $(UNAME)), MINGW64)
    ARCH=x64
  else ifeq ($(findstring MINGW32, $(UNAME)), MINGW32)
    ARCH=x86
  else
    UNAME := $(shell uname -m)
    ifeq ($(UNAME), x86_64)
      ARCH=x64
    else ifeq ($(UNAME), aarch64)
      ARCH=arm64
    else
      ARCH=x86
    endif
  endif
endif

INCLUDES=-Isrc -I./src/libchdr/deps/miniz-3.1.2 -I./src/rcheevos/include
CFLAGS=-Wall $(INCLUDES)
CXXFLAGS=$(CFLAGS) -std=c++11
LDFLAGS=-static-libgcc -static-libstdc++

ifeq ($(ARCH), x86)
  CFLAGS += -m32
  CXXFLAGS += -m32
  LDFLAGS += -m32
  OUTDIR=bin
else ifeq ($(ARCH), x64)
  CFLAGS += -m64
  CXXFLAGS += -m64
  LDFLAGS += -m64
  OUTDIR=bin64
else ifeq ($(ARCH), arm64)
  CFLAGS += -march=armv8-a
  CXXFLAGS += -march=armv8-a
  LDFLAGS += -march=armv8-a
  OUTDIR=bin64
else
  $(error unknown ARCH "$(ARCH)")
endif

ifneq ($(DEBUG),)
  CFLAGS   += -O0 -g
  CXXFLAGS += -O0 -g
else
  CFLAGS   += -O3 -DNDEBUG
  CXXFLAGS += -O3 -DNDEBUG
endif

ifdef HAVE_CHD
  CXXFLAGS += -DHAVE_CHD -I./src/libchdr/include
  CFLAGS += -DZ7_ST -DZSTD_DISABLE_ASM -I./src/libchdr/include -I./src/libchdr/deps/lzma-26.02/include -I./src/libchdr/deps/zlib-1.3.1 -I./src/libchdr/deps/zstd-1.5.6/lib
# NOTE: libchdr provides a miniz-3.1.2 dependency, but RAlibretro also depends
#       on miniz, so it will pull in that dependency directly and we don't have
#       to conditionally pull it in for HAVE_CHD builds.
#            src/libchdr/deps/miniz-3.1.2/miniz.o
  CHD_OBJS = src/libchdr/deps/lzma-26.02/src/LzmaDec.o \
             src/libchdr/deps/zstd-1.5.7/zstddeclib.o \
             src/libchdr/src/libchdr_bitstream.o \
             src/libchdr/src/libchdr_cdrom.o \
             src/libchdr/src/libchdr_chd.o \
             src/libchdr/src/libchdr_codec_avhuff.o \
             src/libchdr/src/libchdr_codec_cdfl.o \
             src/libchdr/src/libchdr_codec_cdlz.o \
             src/libchdr/src/libchdr_codec_cdzl.o \
             src/libchdr/src/libchdr_codec_cdzs.o \
             src/libchdr/src/libchdr_codec_flac.o \
             src/libchdr/src/libchdr_codec_huff.o \
             src/libchdr/src/libchdr_codec_lzma.o \
             src/libchdr/src/libchdr_codec_zlib.o \
             src/libchdr/src/libchdr_codec_zstd.o \
             src/libchdr/src/libchdr_flac.o \
             src/libchdr/src/libchdr_huffman.o
endif
