//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RA_Shared.rc
//
#define IDD_RA_RICHPRESENCE             114
#define IDC_RA_RICHPRESENCERESULTTEXT   1022
#define IDD_RA_MEMORY                   1501
#define IDD_RA_ACHIEVEMENTS             1502
#define IDD_RA_ACHIEVEMENTEDITOR        1503
#define IDD_RA_LOGIN                    1504
#define IDD_RA_GAMETITLESEL             1505
#define IDD_RA_ACHIEVEMENTPROGRESS      1506
#define IDD_RA_LEADERBOARDEDITOR        1507
#define IDD_RA_REPORTBROKENACHIEVEMENTS 1508
#define IDD_RA_GAMELIBRARY              1509
#define IDD_RA_ROMCHECKSUM              1510
#define IDC_RA_TESTVAL                  1512
#define IDC_RA_DOTEST                   1513
#define IDC_RA_MEMSAVENOTE              1514
#define IDC_RA_ADDNOTE                  1515
#define IDC_RA_REMNOTE                  1516
#define IDC_RA_UPLOAD_BADGE             1517
#define IDC_RA_INFO_GG                  1519
#define IDC_RA_MEM_LIST                 1520
#define IDC_RA_HELP                     1521
#define IDC_RA_CHEEVOPIC                1522
#define IDC_RA_REVERTSELECTED           1523
#define IDC_RA_RESET_ACH                1524
#define IDC_RA_CHK_SHOW_DECIMALS        1526

#define IDC_RA_DELETECOND               1527
#define IDC_RA_COPYCOND                1528
#define IDC_RA_ACH_ID                   1529
#define IDC_RA_DEL_ACH                  1530
#define IDC_RA_DELETECOND2              1530
#define IDC_RA_PASTECOND                1530
#define IDC_RA_CHKACHPROCESSINGACTIVE   1531
#define IDC_RA_GOTOWIKI                 1532
#define IDC_RA_GAMEHASH                 1533
#define IDC_RA_NUMACH                   1534
#define IDC_RA_PASSWORD                 1535
#define IDC_RA_SAVEPASSWORD             1536
#define IDC_RA_ACTIVE_CORE              1537
#define IDC_RA_ACTIVE_UNOFFICIAL        1538
#define IDC_RA_ACTIVE_LOCAL             1539
#define IDC_RA_LISTACHIEVEMENTS         1540
#define IDC_RA_ACH_TITLE                1541
#define IDC_RA_ADD_ACH                  1542
#define IDC_RA_ACH_POINTS               1543
#define IDC_RA_CLONE_ACH                1544
#define IDC_RA_LBX_CONDITIONS           1545
#define IDC_RA_ACH_AUTHOR               1546
#define IDC_RA_ADDCOND                  1547
#define IDC_RA_ACH_DESC                 1548
#define IDC_RA_USERNAME                 1549
#define IDC_RA_DOWNLOAD_ACH             1550
#define IDC_RA_COMMIT_ACH               1551
#define IDC_RA_PROMOTE_ACH              1552
#define IDC_RA_CBO_4BIT                 1553
#define IDC_RA_CBO_8BIT                 1554
#define IDC_RA_CBO_16BIT                1555
#define IDC_RA_CBO_32BIT                1556
#define IDC_RA_WATCH                    1557
#define IDC_RA_WATCHING                 1558
#define IDC_RA_CBO_CMPTYPE              1559
#define IDC_RA_CBO_LASTKNOWNVAL         1560
#define IDC_RA_CBO_GIVENVAL             1561
#define IDC_RA_ACH_AUTHOR2              1562
#define IDC_RA_GAMETITLE                1563
#define IDC_RA_BADGENAME                1564
#define IDC_RA_KNOWNGAMES               1565
#define IDC_RA_CHECKSUM                 1566
#define IDC_RA_MEMBANK                  1567
#define IDC_RA_ACHPROGRESS_FORMULA      1569
#define IDC_RA_ACHPROGRESS_EXAMPLE      1570
#define IDC_RA_ACHPROGRESSENABLE        1571
#define IDC_RA_ACHPROGRESS_FORMATTING   1572
#define IDC_RA_ACHPROGRESS_MAXIMUM      1573
#define IDC_RA_ACTIVATE_ALL_ACH         1574
#define IDC_RA_ACH_GROUP                1575
#define IDC_RA_ACH_DELGROUP             1576
#define IDC_RA_ACH_ADDGROUP             1577
#define IDC_RA_PROGRESSINDICATORS       1578
#define IDC_RA_MEMVIEW8BIT              1579
#define IDC_RA_MEMVIEW16BIT             1580
#define IDC_RA_MEMVIEW32BIT             1581
#define IDC_RA_MEMTEXTVIEWER            1582
#define IDC_RA_MEMBITS                  1583
#define IDC_RA_MEMBITS_TITLE            1584
#define IDC_RA_REPORTBROKENACHIEVEMENTSLIST 1586
#define IDC_RA_BROKENACHIEVEMENTREPORTCOMMENT 1587
#define IDC_RA_PROBLEMTYPE1             1588
#define IDC_RA_PROBLEMTYPE2             1589
#define IDC_RA_BROKENACH_BUGREPORTER    1590
#define IDC_RA_RESCAN                   1591
#define IDC_RA_LBX_GAMELIST             1592
#define IDC_RA_ROMDIR                   1593
#define IDC_RA_GLIB_NAME                1594
#define IDC_RA_PICKROMDIR               1595
#define IDC_RA_REFRESH                  1596
#define IDC_RA_SCANNERFOUNDINFO         1597
#define IDC_RA_ROMCHECKSUMTEXT          1598
#define IDC_RA_COPYCHECKSUMCLIPBOARD    1599
#define IDC_RA_CBO_SEARCHALL            1600
#define IDC_RA_CBO_SEARCHCUSTOM         1601
#define IDC_RA_CBO_SEARCHSYSTEMRAM      1602
#define IDC_RA_CBO_SEARCHGAMERAM        1603
#define IDC_RA_SEARCHRANGE              1604
#define IDM_RA_MENUSTART                1700
#define IDM_RA_RETROACHIEVEMENTS        1700
#define IDM_RA_FILES_TEST1              1701
#define IDM_RA_FILES_TEST2              1702
#define IDM_RA_FILES_CHECKFORUPDATE     1703
#define IDM_RA_FILES_ACHIEVEMENTS       1704
#define IDM_RA_FILES_MEMORYFINDER       1705
#define IDM_RA_FILES_LOGIN              1706
#define IDM_RA_FILES_LOGOUT             1707
#define IDM_RA_FILES_ACHIEVEMENTEDITOR  1708
#define IDM_RA_FILES_LEADERBOARDEDITOR  1709
#define IDM_RA_HARDCORE_MODE            1710
#define IDM_RA_REPORTBROKENACHIEVEMENTS 1711
#define IDM_RA_GETROMCHECKSUM           1712
#define IDM_RA_OPENUSERPAGE             1713
#define IDM_RA_OPENGAMEPAGE             1714
#define IDM_RA_SCANFORGAMES             1715
#define IDM_RA_PARSERICHPRESENCE        1716
#define IDM_RA_TOGGLELEADERBOARDS       1717
#define IDM_RA_MENUEND                  1739
#define IDC_RA_OPENPAGE                 1740

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
